name: "Create a jar when there is a new release tag"

on: # a new tag will launch the jobs 
  push:
    tags:
      - "v*.*.*"

jobs:
  release-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --update-snapshots --batch-mode clean package
      
      - name: Build maven javadoc
        run: mvn javadoc:javadoc && tar -czvf javadocs.tar.gz target/site/apidocs/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            target/dilemme.jar
            javadocs.tar.gz
